#!/bin/bash
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
BOLD=$(tput bold)
RESET=$(tput sgr0)
echo ""
echo ""
echo ""
echo "${YELLOW}"
echo "        ::::::::  :::    ::: :::::::::   ::::::::          ::::::::  :::::::::   ::::::::   ::::::::  :::    :::"
echo "      :+:    :+: :+:    :+: :+:    :+: :+:    :+:        :+:    :+: :+:    :+: :+:    :+: :+:    :+: :+:    :+:"
echo "     +:+        +:+    +:+ +:+    +:+ +:+    +:+        +:+        +:+    +:+ +:+    +:+ +:+        +:+    +:+"   
echo "    +#++:++#++ +#+    +:+ +#+    +:+ +#+    +:+        +#+        +#++:++#:  +#+    +:+ +#++:++#++ +#++:++#++"    
echo "          +#+ +#+    +#+ +#+    +#+ +#+    +#+        +#+        +#+    +#+ +#+    +#+        +#+ +#+    +#+"     
echo "  #+#    #+# #+#    #+# #+#    #+# #+#    #+#        #+#    #+# #+#    #+# #+#    #+# #+#    #+# #+#    #+#"      
echo "  ########   ########  #########   ########          ########  ###    ###  ########   ########  ###    ###${RESET}"       
echo ""                                                  
echo ""
echo ""
curl -L https://raw.githubusercontent.com/shadowed1/sudoCrosh/main/sudocrosh.sh -o /home/chronos/sudocrosh.sh
echo "${BOLD}Downloading sudocrosh.sh to: /home/chronos/${RESET}"   
echo "${BLUE}" 
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║  ${RESET}${YELLOW}${BOLD}HOW TO INSTALL:${RESET}${BLUE}                                             ║"
echo "║                                                              ║"
echo "║  1.) Open crosh shell (ctrl-alt-t), copy paste, and run:     ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo "${RESET}${CYAN}"
echo "curl -L https://raw.githubusercontent.com/shadowed1/sudoCrosh/main/minioverride.so -o /home/chronos/minioverride.so"
echo "${RESET}${MAGENTA}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║  2). In VT-2 (ctrl-alt-F2) login as root and run:            ║"
echo "║      Use Tab key to auto-complete the paths.                 ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo "${RESET}${MAGENTA}${BOLD}"
echo "mv /home/chronos/sudocrosh.sh /usr/local/"
echo "bash /usr/local/sudocrosh.sh"
echo "${RESET}"
echo "${RESET}${YELLOW}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║ Each time ChromeOS gets an update, sudo will be disabled.    ║"
echo "║ In VT-2 (ctrl-alt-F2) login as root and run:                 ║"
echo "║ ${RESET}${BLUE}bash /usr/local/sudocrosh.sh${RESET}${YELLOW}                                 ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo "${RESET}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║              Original guide created by Velzie:               ║"
echo "║                  https://github.com/velzie                   ║"
echo "╚══════════════════════════════════════════════════════════════╝"
