#!/bin/bash
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
BOLD=$(tput bold)
RESET=$(tput sgr0)
echo ""
echo ""
echo ""
echo "${YELLOW}"
echo "        ::::::::  :::    ::: :::::::::   ::::::::          ::::::::  :::::::::   ::::::::   ::::::::  :::    :::"
echo "      :+:    :+: :+:    :+: :+:    :+: :+:    :+:        :+:    :+: :+:    :+: :+:    :+: :+:    :+: :+:    :+:"
echo "     +:+        +:+    +:+ +:+    +:+ +:+    +:+        +:+        +:+    +:+ +:+    +:+ +:+        +:+    +:+"   
echo "    +#++:++#++ +#+    +:+ +#+    +:+ +#+    +:+        +#+        +#++:++#:  +#+    +:+ +#++:++#++ +#++:++#++"    
echo "          +#+ +#+    +#+ +#+    +#+ +#+    +#+        +#+        +#+    +#+ +#+    +#+        +#+ +#+    +#+"     
echo "  #+#    #+# #+#    #+# #+#    #+# #+#    #+#        #+#    #+# #+#    #+# #+#    #+# #+#    #+# #+#    #+#"      
echo "  ########   ########  #########   ########          ########  ###    ###  ########   ########  ###    ###${RESET}"       
echo ""                                                  
echo ""
if [[ -d /home/chronos/user/MyFiles/Downloads ]]; then
    mkdir -p /home/chronos/user/MyFiles/Downloads/.config/shadowed1/sudocrosh
    curl -L https://raw.githubusercontent.com/shadowed1/sudoCrosh/main/sudocrosh.sh -o /home/chronos/sudocrosh
fi
echo "${BOLD}${BLUE}Downloading sudocrosh to: /home/chronos/${RESET}"   
echo "${BLUE}" 
echo "╔═══════════════════════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                                           ║"
echo "║  ${RESET}${YELLOW}${BOLD}HOW TO INSTALL: ${RESET}${BLUE}                                                                         ║"
echo "║                                                                                           ║"
echo "║  1.) Open files app in ChromeOS and right click Downloads folder and share it with Linux. ║"
echo "║  2.) Install Linux development environment and start it up.                               ║"
echo "║  ${BOLD}Steps 1 and 2 can be skipped if using Chard${RESET}${BLUE}                                              ║"
echo "║                                                                                           ║"

echo "╚═══════════════════════════════════════════════════════════════════════════════════════════╝"
echo "${RESET}${CYAN}"
echo "╔═══════════════════════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                                           ║"
echo "║  3a). In ${BOLD}Crostini${RESET}${CYAN}, copy paste and run:                                                    ║"
echo "║                                                                                           ║"
echo "╚═══════════════════════════════════════════════════════════════════════════════════════════╝"
echo "${RESET}${CYAN}${BOLD}"
echo "sudo curl -fsSL https://raw.githubusercontent.com/shadowed1/sudoCrosh/main/sudocrosh_crostini.sh -o /bin/sudocrosh_crostini"
echo "sudo chmod +x /bin/sudocrosh_crostini"
echo "/bin/sudocrosh_crostini"
echo "${RESET}${RED}"
echo "╔═══════════════════════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                                           ║"
echo "║  3b). OR in ${BOLD}Chard${RESET}${RED}, copy paste and run:                                                    ║"
echo "║                                                                                           ║"
echo "╚═══════════════════════════════════════════════════════════════════════════════════════════╝"
echo "${RESET}${RED}${BOLD}"
echo "mkdir -p /home/chronos/user/MyFiles/Downloads/.config/shadowed1/sudocrosh/"
echo "curl -L https://raw.githubusercontent.com/shadowed1/sudoCrosh/main/minioverride.c -o /home/chronos/user/MyFiles/Downloads/.config/shadowed1/sudocrosh/minioverride.c"
echo "gcc /home/chronos/user/MyFiles/Downloads/.config/shadowed1/sudocrosh/minioverride.c -o /home/chronos/user/MyFiles/Downloads/.config/shadowed1/sudocrosh/minioverride.so -shared"
echo "${RESET}${MAGENTA}"
echo "╔═══════════════════════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                                           ║"
echo "║  4). In VT-2 (ctrl-alt-refresh) login as root and run these two commands:                 ║"
echo "║                                                                                           ║"
echo "╚═══════════════════════════════════════════════════════════════════════════════════════════╝"
echo "${RESET}${MAGENTA}${BOLD}"
echo "cp /home/chronos/sudocrosh /usr/local/"
echo "bash /usr/local/sudocrosh"
echo "${RESET}${YELLOW}"
echo "╔═══════════════════════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                                           ║"
echo "║ Each time ChromeOS gets an update, sudo will be disabled again.                           ║"
echo "║ In VT-2 (ctrl-alt-F2) login as root and run:                                              ║"
echo "║ ${RESET}${BLUE}bash /usr/local/sudocrosh${RESET}${YELLOW}                                                                 ║"
echo "║                                                                                           ║"
echo "╚═══════════════════════════════════════════════════════════════════════════════════════════╝"
echo "${RESET}"
echo "╔═══════════════════════════════════════════════════════════════════════════════════════════╗"
echo "║              Original guide created by Velzie:                                            ║"
echo "║                  https://github.com/velzie                                                ║"
echo "╚═══════════════════════════════════════════════════════════════════════════════════════════╝"
