#!/bin/bash
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
BOLD=$(tput bold)
RESET=$(tput sgr0)
echo ""
echo ""
echo ""
echo "${YELLOW}"
echo "        ::::::::  :::    ::: :::::::::   ::::::::          ::::::::  :::::::::   ::::::::   ::::::::  :::    :::"
echo "      :+:    :+: :+:    :+: :+:    :+: :+:    :+:        :+:    :+: :+:    :+: :+:    :+: :+:    :+: :+:    :+:"
echo "     +:+        +:+    +:+ +:+    +:+ +:+    +:+        +:+        +:+    +:+ +:+    +:+ +:+        +:+    +:+"   
echo "    +#++:++#++ +#+    +:+ +#+    +:+ +#+    +:+        +#+        +#++:++#:  +#+    +:+ +#++:++#++ +#++:++#++"    
echo "          +#+ +#+    +#+ +#+    +#+ +#+    +#+        +#+        +#+    +#+ +#+    +#+        +#+ +#+    +#+"     
echo "  #+#    #+# #+#    #+# #+#    #+# #+#    #+#        #+#    #+# #+#    #+# #+#    #+# #+#    #+# #+#    #+#"      
echo "  ########   ########  #########   ########          ########  ###    ###  ########   ########  ###    ###${RESET}"       
echo ""                                                  
echo ""
echo ""
curl -L https://raw.githubusercontent.com/shadowed1/ChromeOS_PowerControl/main/sudocrosh.sh -o /home/chronos/sudocrosh.sh
echo "${BOLD}Downloading sudocrosh.sh to: /home/chronos/${RESET}"   
echo "${BLUE}" ${RESET}${BLUE}${BOLD}${RESET}${BLUE}
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║  HOW TO INSTALL:                                             ║"
echo "║                                                              ║"
echo "║  1.) Install Linux development environment and start it up.  ║"
echo "║  2.) Open crosh shell (ctrl-alt-t), copy paste, and run:     ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo "${RESET}${BLUE}${BOLD}"
echo "vmc share termina Downloads"
echo "${RESET}${CYAN}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║  3). In Crostini, copy paste and run:                        ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo "${RESET}${CYAN}${BOLD}"
echo "sudo apt-get update"
echo "sudo apt install gcc"
echo "curl -L https://raw.githubusercontent.com/shadowed1/sudoCrosh/main/minioverride.c -o /mnt/chromeos/MyFiles/Downloads/minioverride.c"
echo "gcc /mnt/chromeos/MyFiles/Downloads/minioverride.c -o /mnt/chromeos/MyFiles/Downloads/minioverride.so -shared"
echo "${RESET}${MAGENTA}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║  4). In VT-2 (ctrl-alt-forward) login as root and run:       ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo "${RESET}${MAGENTA}${BOLD}"
echo "sudo mv /home/chronos/sudocrosh.sh /usr/local/"
echo "sudo chmod +x /usr/local/sudocrosh.sh"
echo "sudo bash /usr/local/sudocrosh.sh"
echo "${RESET}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║             Original guide created by Velzie:                ║"
echo "║                 https://github.com/velzie                    ║"
echo "╚══════════════════════════════════════════════════════════════╝"
